name: gait_detector
description: 步态检测APP - 通过蓝牙连接4个传感器实时采集步态数据
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
